- hosts: localhost
  vars:
    username: "{{ ansible_user_id }}"
  pre_tasks:
    - name: Upgrade everything
      become: true
      dnf:
        name: "*"
        state: latest
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/system.yml
    - import_tasks: tasks/tools.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/git.yml
    - import_tasks: tasks/terminal.yml
    - import_tasks: tasks/programs.yml
    - import_tasks: tasks/fonts.yml
