- hosts: localhost
  pre_tasks:
    - name: Upgrade everything
      become: true
      dnf:
        name: "*"
        state: latest
  tasks:
    - name: Setup ssh keys
      include_tasks: tasks/ssh.yml
    - name: Setup git config
      include_tasks: tasks/git.yml
    - name: install dotfiles
      include_tasks: tasks/dotfiles.yml
    - name: Install and configure the terminal
      include_tasks: tasks/terminal.yml
