- name: Clone dotfiles
  git:
    repo: https://github.com/maiksch/.dotfiles
    dest: ~/dotfiles

- name: Install stow
  become: true
  dnf:
    name: stow
    state: latest

- name: Create symlinks
  shell: cd ~/dotfiles && sudo chmod 775 ./install && ./install
