- name: Install git
  become: true
  dnf:
    name: git
    state: latest

- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "maik.schmaddebeck@icloud.com"

- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "Maik Schmaddebeck"

- name: Ensure work folder exists
  file:
    name: ~/work/
    state: directory

- name: Git work overwrite email
  git_config:
    name: user.email
    scope: file
    file: ~/work/.gitconfig
    value: "maik.schmaddebeck@point-gmbh.com"
