- name: Install dnf plugins
  become: true
  dnf: name=dnf-plugins-core

# Install Brave Browser
- name: Add brave repository to dnf
  become: true
  shell: |
    dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/
    rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

- name: Install Brave
  become: true
  dnf: name=brave-browser

# Install Postman
- name: Install Postman
  become: true
  shell:
    #chdir: /tmp
    cmd: |
      wget -O /tmp/postman.tar.gz https://dl.pstmn.io/download/latest/linux64
      tar -xz -f /tmp/postman.tar.gz --directory /opt
      cp files/postman.desktop /usr/local/share/applications/

# Install 1password
- name: Add 1password repository to dnf
  become: true
  shell: |
    sh -c 'echo -e "[1password]\nname=1Password Stable Channel\nbaseurl=https://downloads.1password.com/linux/rpm/stable/\$basearch\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=\"https://downloads.1password.com/linux/keys/1password.asc\"" > /etc/yum.repos.d/1password.repo'
    rpm --import https://downloads.1password.com/linux/keys/1password.asc

- name: Install 1password
  become: true
  dnf: name=1password

# Install Thunderbird
- name: Install Thunderbird
  become: true
  dnf: name=thunderbird
