- name: Install stuff
  become: true
  dnf:
    name: [git, openssl, which, wget, util-linux-user]

- name: Install window manager packages
  become: true
  dnf:
    name:
      [bspwm, sxhkd, xsetroot, polybar, feh, rofi, arandr, picom, xinput, sway]
