- name: Install utils
  become: true
  dnf:
    name: [git, openssl, which, util-linux-user, ripgrep, wget, xclip, brightnessctl, nss-tools]

- name: Install window manager packages
  become: true
  dnf:
    name:
      [bspwm, sxhkd, xsetroot, polybar, feh, rofi, arandr, picom, xinput, network-manager-applet]
