- name: Install stuff
  become: true
  dnf:
    name: [git, openssl, which, util-linux-user]

- name: Install utils
  become: true
  dnf:
    name: [ripgrep, wget, xclip]

- name: Install window manager packages
  become: true
  dnf:
    name:
      [bspwm, sxhkd, xsetroot, polybar, feh, rofi, arandr, picom, xinput, network-manager-applet]
