- name: Install zsh
  become: true
  dnf:
    name: [zsh, kitty, neovim, tmux, fzf]
    state: latest

- name: Change default shell
  become: true
  shell: "chsh -s $(which zsh) {{ username }}"

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --keep-zshrc

- name: Install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/plugins/zsh-autosuggestions
    depth: 1

- name: Install zsh theme
  shell: |
    mkdir -p ~/.oh-my-zsh/custom/themes
    cp files/maiksch.zsh-theme ~/.oh-my-zsh/custom/themes/

- name: Install neovim packer
  git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    depth: 1
