- name: Install languages
  become: true
  dnf:
    name: [dotnet, dotnet-sdk-3.1, golang, elixir, erlang]
    state: latest

- name: Install volta
  shell: curl -s https://get.volta.sh | bash

- name: Install node
  shell: volta install node
  environment:
    PATH: "$PATH:/home/{{ username }}/.volta/bin"

- name: Install Angular
  npm:
    name: "@angular/cli"
    global: yes
  environment:
    PATH: "$PATH:/home/{{ username }}/.volta/bin"

- name: Install hex and pheonix (for elixir)
  shell: |
    echo "Y" | mix local.hex
    echo "Y" | mix archive.install hex phx_new
