- name: Install dotnet
  become: true
  dnf:
    name: [dotnet, dotnet-sdk-3.1]

- name: Install volta
  shell: curl -s https://get.volta.sh | bash

- name: Install node
  shell: ~/.volta/bin/volta install node

- name: Install Angular
  npm:
    name: "@angular/cli"
    global: yes
