- name: Install dotnet
  become: true
  dnf:
    name: [dotnet, dotnet-sdk-3.1]
    state: latest

- name: Install golang
  become: true
  dnf: name=golang

- name: Install volta
  shell: curl -s https://get.volta.sh | bash

- name: Install node
  shell: volta install node
  environment:
    PATH: "$PATH:/home/{{ username }}/.volta/bin"

- name: Install Angular
  npm:
    name: "@angular/cli"
    global: yes
  environment:
    PATH: "$PATH:/home/{{ username }}/.volta/bin"
